### ISSUE TITLE
updating embedded cu-fake-api

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/cu-build-tools#26]
How do I get build tools to pick up a new version of CUFakeGameAPI that it injects?  Where is it pulling it from?

I wonder if it would be better to add cu-fake-api off root of cu-ui-v2, and have the server inject the following script instead:

```html
<script src="../node_modules/cu-fake-api/lib/main.js"></script> 
```

The cu-ui-v2 can be in control of which version of cu-fake-api it tests with.

**Comment by saddieeiddas** [comment]
The tools are located at `node_modules\cu-build-tools\node_modules\cu-fake-api` .. if you go to `node_modules/cu-build-tools` you can run `npm update cu-fake-api` there.

**Comment by Mehuge** [comment]
@saddieeiddas I tried that and it didn't seem to work, though I accept it should.  I removed cu-fake-api from cu-build-tools and npm installed it in the root of cu-ui-v2 and it works there as well.  The advantage of having it as a dependency of my project is I am in control which version of the API it uses, it is also easier (slightly) to update.

**Comment by saddieeiddas** [comment]
Good thoughts here.

I think i will make a `injected_scripts` option for the server config, so everything can specify custom scripts, or remove existing ones etc.

**Comment by saddieeiddas** [comment]
This is all working now, you can completely configure all injected scripts, and by default it will look for fake api in top level, falling back to the fake api installed by build-tools
