### ISSUE TITLE
Turning off automatic install not working

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/cu-build-tools#33]
Since I updated all my node modules and picked up latest build tools my cu-ui-v2 project now insists on always doing an install before doing a build.  I tried gulp --no-install and --no-install-npm and it is still doing an install.

When working on library stuff, my work flow is:

1. Change library code
2. gulp publish
3. Run a special script I have that rebuilds my libraries in turn, and updates all node_modules instances of them with the latest lib code
4. gulp publish on cu-ui-v2

Step 4 now undoes step 3

This means I cannot test with library changes because it overwrites my updated library code in node_modules.  This in turn means that I can't build the project as a whole, instead I have to go into each individual UI module folder and do a gulp publish to avoid the install.

I added some debugs (console.logs) to loacConfig.js and got the following results:

    D:\dev\cu\mehuge\2\cu-ui-v2> gulp --no-install-npm publish
    ARGV {"_":["publish"],"install-npm":false}
    AFTER config.build 
        {"compress":false,"vsgen":false,"install_npm":false,"install_tsd":true,
        "publish":false,"server":false,"sourcemaps":true,"sourcemaps_inline":false,
        "is_multi":false,"ui_nested":false}
    [13:04:39] Using gulpfile D:\dev\cu\mehuge\2\cu-ui-v2\gulpfile.js
    [13:04:39] Starting 'install'...
    [13:04:39] Starting 'install:libraries'...
    [13:04:39] Finished 'install:libraries' after 203 μs
    [13:04:39] Starting 'install:subdirectories'...
    [13:04:39] gulp-chug-pretty started                                                                                                                    
    [13:04:39] Spawning Process In D:\dev\cu\mehuge\2\cu-ui-v2\apitest
         With Args: D:\dev\cu\mehuge\2\cu-ui-v2\node_modules\gulp\bin\gulp.js
         --gulpfile gulpfile.js install --install                                                                                                                              
    ARGV {"_":["install"],"gulpfile":"gulpfile.js","install":true}                                                                                         

So it seems to initially recognise the --no-install-npm but then proceeds to run install on each module anyway.

**Comment by saddieeiddas** [comment]
Nice spot.

There is definitely an issue with passing the command line flags to the sub tasks.

This is due to https://github.com/CUModSquad/cu-build-tools/blob/master/src/util/subTaskUtil.js#L123 Not looking for the `no-` arguments.

I will fix this and create a new PR.

**Comment by saddieeiddas** [comment]
This is fixed, should work now passing `--no-install` or `--no-install-npm` along with all the other `--no` arguments.
