### ISSUE TITLE
%LOCALAPPDATA% ... INTERFACE friendly publish

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/cu-build-tools#34]
With the new directory structure of the CU client and removal of support for uiCustomFilePath it is more   fiddly to test UIs you are developing.

So imagine this scenario:-

1. Game client installed.
2. Several community UI mods installed (in my case, many of my own UI 1.0 UIs, + Ortu UIs)
3. Working on a bunch of UI 2.0 UIs

At the moment, with build tools, the only options for testing seem to be:

1. Inject a cu-fake-api and test in browser 
2. Manually copy publish output contents to that unwieldy path name
3. Write some extra script to run post publish to do the copies

Two issues exist in build tools that prevent it using the INTERFACE folder as the publish destination:

1. If pointing dest directly at the INTERFACE folder under local appdata, we thankfully get this error from the del module: "Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.'"
2. We don't want to delete the contents of the publish destination, only the modules in that location we are about to replace.

I think we can assume uiCustomFilePath won't be making a comback, so making cu-build-tools more INTERFACE folder friendly would be useful.

**Comment by Mehuge** [comment]
Something to think about as well is if we want to have the full interface folder path in the build config, or want some other way to specify to build to the interface folder.  e.g. having the local publish a junction to the actual interface folder.

**Comment by saddieeiddas** [comment]
I have a PR here #32 which adds a flag to publish to the interface folder.

This should allow you to have your UI folder wherever you want, but still be able to publish to the User UI directory.

**Comment by saddieeiddas** [comment]
This is fixed now, README is updated with instructions on how to make it install to User UI folder.

https://github.com/CUModSquad/cu-build-tools#--user-ui
